package basico.jdbc;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class TableManager {

	public void createUserTable() {

		Connection c = DBManager.getInstance().connect();
		
		System.out.println(c);
		String sql = "CREATE TABLE IF NOT EXISTS empleado(legajo INTEGER GENERATED BY DEFAULT AS IDENTITY, nombre VARCHAR(100), apellido VARCHAR(100), dni INTEGER, "
					+ "direccion VARCHAR(100), honorarios DECIMAL(7,2), nombreUsuario VARCHAR(20), password VARCHAR(20))";
		
		try {
			Statement s = c.createStatement();
			Boolean rs = s.execute(sql);
			System.out.println(rs);
		} catch (SQLException e) {
			try {
				c.rollback();
				e.printStackTrace();
			} catch (SQLException e1) {
				e1.printStackTrace();
			}
		} finally {
			try {
				c.close();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		

	}
	
	public void dropUserTable() {

		Connection c = DBManager.getInstance().connect();
		
		String sql = "DROP TABLE empleado";
		
		try {
			Statement s = c.createStatement();
			s.execute(sql);
			c.commit();
		} catch (SQLException e) {
			try {
				c.rollback();
			} catch (SQLException e1) {
				e1.printStackTrace();
			}
		} finally {
			try {
				c.close();
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
		

	}
	
	public void createTareaTable() {

		Connection c = DBManager.getInstance().connect();
		
		System.out.println(c);
		String sql = "CREATE TABLE tarea(id INTEGER, nombre VARCHAR(100), descripcion VARCHAR(200), horas INTEGER, legajoEmpleado INTEGER)";
		
		try {
			Statement s = c.createStatement();
			Boolean rs = s.execute(sql);
			System.out.println(rs);
		} catch (SQLException e) {
			try {
				c.rollback();
				e.printStackTrace();
			} catch (SQLException e1) {
				e1.printStackTrace();
			}
		} finally {
			try {
				c.close();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		

	}

}
